spring:
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    show-sql: false
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./tdb;AUTO_SERVER=TRUE;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  mvc:
    static-path-pattern: /static/**
    path match: # 스웨거 경로 설정
      matching-strategy: ant_path_matcher
  auditing:
    enabled: true # Auditing 활성화
  sql:
    init:
      mode: always
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: cnustudent0@gmail.com
    password: fwcd lfef ajcs utyu
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


server:
  port: 8080
  error:
    whitelabel:
      enabled: false


logging:
  level:
    root: info
    org:
      hibernate:
        type: info

jwt: # HS256 알고리즘으로 복호화 하기 위해 256비트 이상의 키 가 필요
  secret: asdf1zxcvp,qwefqwe21;3lm12;rasdf
  expiredMs: 50000
